language: node_js
node_js:
  - '8'
install:
  - 'bash ./run_cypress_e2e.sh prepare-images'
script:
  - 'bash ./run_cypress_e2e.sh run'
cache:
  directories:
  - "$HOME/.npm"
deploy:
  provider: script
  script: './deploy_dockerhub.sh'
  on:
    branch: master
