language: node_js
node_js:
  - '8'
install:
  # pull images & build stuff needed by e2e tests
  - 'bash ./run_cypress_e2e.sh prepare-images'
script:
  - 'bash ./run_cypress_e2e.sh run'
cache: npm
deploy:
  provider: script
  script: './deploy_dockerhub.sh'
  on:
    branch: master
