language: node_js
node_js:
  - '8'
install:
  # pull images needed by e2e tests
  - 'bash ./run_cypress_e2e.sh install'
  # run install to get cypress
  - npm install
script:
  - 'bash ./run_cypress_e2e.sh run && npm run build'
deploy:
  provider: script
  script: "./deploy_dockerhub.sh"
  on:
    branch: master