services:
  db:
    image: postgres:10.6
    restart: always
    ports:
      - '5432:5432'
    environment:
      PGDATA: /data/test
      POSTGRES_DB: ci_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 10s
      retries: 60
    volumes:
    # Uses a tmpfs volume to make tests extremely fast. The data in test
    # databases is not persisted across restarts, nor does it need to be.
    - type: tmpfs
      target: /data/test

  backend-test:
    build: 
      context: './backend'
      dockerfile: Dockerfile.dev
    restart: no
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ci_postgres
      - SECRET=testsecret
      - EMAIL_ENABLED=false
      - PORT=3001
    command:
      - /bin/sh
      - -c
      - |
        cd /usr/src/app
        npm install
        npm run db:migrate
        npm run test

  backend:
    build: 
      context: './backend'
      dockerfile: Dockerfile
    restart: always
    ports:
      - '7001:3001'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SECRET=yoursecrethere
      - EMAIL_ENABLED=false
      - DATABASE_URL=postgres://postgres@db:5432/ci_postgres

  frontend:
    build: 
      context: './frontend'
      dockerfile: Dockerfile
    ports:
      - '7000:3000'
    depends_on:
      - db
      - backend
    environment:
      - PUBLIC_URL=http://localhost:7001

  nginx:
    image: nginx:1.25.4
    ports:
      - '3000:80'
    restart: always
    volumes:
      - ./frontend/e2e/nginx.e2e.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
