version: '2'
services:
  nginx:
    image: ohtuprojektiilmo/e2e-nginx
    build: .
    ports:
      - '3000:80'
    restart: always
    depends_on:
      - frontend
      - backend

  frontend:
    image: ohtuprojektiilmo/ohtufront
    build: '.'
    expose:
      - '3000'
    depends_on:
      - backend
      - db

  backend:
    image: ohtuprojektiilmo/ohtuback
    restart: always
    expose:
      - '3001'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SECRET=yoursecrethere

  db:
    image: postgres:10.6
    restart: always
    expose:
      - '5432'
    environment:
      PGDATA: /data/test
    volumes:
      - pg-data:/data/test

volumes:
  pg-data:
