version: '2'
services:
  frontend:
    # you can put your local image instead of ohtuprojektiilmo/ohtufront if you want
    image: quay.io/ohtuilmo/frontend
    build: './frontend'
    ports:
      - '7000:3000'
    depends_on:
      - backend
      - db

  backend:
    image: quay.io/ohtuilmo/backend
    build: './backend'
    restart: always
    ports:
      - '7001:3001'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SECRET=yoursecrethere
      - EMAIL_ENABLED=false
      - DATABASE_URL=postgres://postgres@db:5432/dev_postgres

  db:
    image: postgres:10.6
    restart: always
    ports:
      - '5432:5432'
    environment:
      PGDATA: /data/test
    volumes:
      - pg-data:/data/test

volumes:
  pg-data:
