name: Deploy to production

on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Build backend
        id: build-backend
        uses: redhat-actions/buildah-build@v2
        with:
          image: backend
          tags: production ${{ github.sha }}
          context: backend/
          containerfiles: |
            backend/Dockerfile

      - name: Build frontend
        id: build-frontend
        uses: redhat-actions/buildah-build@v2
        with:
          image: frontend
          tags: production ${{ github.sha }}
          context: frontend/
          containerfiles: |
            frontend/Dockerfile

      - name: Push backend to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-backend.outputs.image }}
          tags: ${{ steps.build-backend.outputs.tags }}
          registry: quay.io/ohtuilmo
          username: ohtuilmo+github
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Push frontend to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-frontend.outputs.image }}
          tags: ${{ steps.build-frontend.outputs.tags }}
          registry: quay.io/ohtuilmo
          username: ohtuilmo+github
          password: ${{ secrets.QUAY_PASSWORD }}
