name: Deploy to staging

on:
  push:
    branches:
      - main
      - redfox-workflow_rewrite

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Push backend to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ needs.test.steps.build-backend.outputs.image }}
          tags: ${{ needs.test.steps.build-backend.outputs.tags }}
          registry: quay.io/ohtuilmo
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Push frontend to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ needs.test.steps.build-frontend.outputs.image }}
          tags: ${{ needs.test.steps.build-frontend.outputs.tags }}
          registry: quay.io/ohtuilmo
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}