name: Run tests

on: [workflow_call]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12.22.12
      - name: Install backend dependencies & run linter
        working-directory: ./backend
        run: |
          npm ci
          npm run lint
      - name: Install frontend dependencies & run linter
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint

      - name: Build backend
        id: build-backend
        uses: redhat-actions/buildah-build@v2
        with:
          image: backend
          tags: latest ${{ github.sha }}
          context: backend/
          containerfiles: |
            backend/Dockerfile

      - name: Build frontend
        id: build-frontend
        uses: redhat-actions/buildah-build@v2
        with:
          image: frontend
          tags: latest ${{ github.sha }}
          context: frontend/
          containerfiles: |
            frontend/Dockerfile
