name: Run tests

on: [workflow_call]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12.22.12
      - name: Install backend dependencies & run linter
        working-directory: ./backend
        run: |
          npm ci
          npm run lint:fix
      - name: Install frontend dependencies & run linter
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint:fix
